# Generated by Django 5.1.7 on 2025-04-22 09:44

import django.db.models.deletion
import lezioni.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_registrationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False, help_text='Se la lezione è visibile agli studenti assegnati.')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lezione',
                'verbose_name_plural': 'Lezioni',
            },
        ),
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('html', 'Contenuto HTML'), ('pdf', 'Documento PDF'), ('ppt', 'Presentazione PPT/PPTX'), ('url', 'Link Esterno')], max_length=10, verbose_name='Tipo di Contenuto')),
                ('html_content', models.TextField(blank=True, help_text='Usare per Contenuto HTML.', verbose_name='Contenuto HTML')),
                ('file', models.FileField(blank=True, help_text='Usare per PDF, PPT, ecc.', null=True, upload_to=lezioni.models.lesson_content_upload_path, verbose_name='File Caricato')),
                ('url', models.URLField(blank=True, help_text='Usare per Link Esterno.', verbose_name='URL Esterno')),
                ('title', models.CharField(blank=True, help_text='Titolo opzionale per questo blocco di contenuto', max_length=255, verbose_name='Titolo Contenuto')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione nella lezione.', verbose_name='Ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='lezioni.lesson')),
            ],
            options={
                'verbose_name': 'Contenuto Lezione',
                'verbose_name_plural': 'Contenuti Lezione',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materie',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_topics', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='lezioni.subject')),
            ],
            options={
                'verbose_name': 'Argomento',
                'verbose_name_plural': 'Argomenti',
                'unique_together': {('name', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='lezioni.topic'),
        ),
        migrations.CreateModel(
            name='LessonAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, help_text='Data e ora prima visualizzazione da parte dello studente', null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_lesson_assignments', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lezioni.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='users.student')),
            ],
            options={
                'verbose_name': 'Assegnazione Lezione',
                'verbose_name_plural': 'Assegnazioni Lezioni',
                'ordering': ['-assigned_at'],
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
