# Generated by Django 5.1.7 on 2025-04-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lezioni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonassignment',
            options={'ordering': ['lesson', 'group', 'student'], 'verbose_name': 'Assegnazione Lezione', 'verbose_name_plural': 'Assegnazioni Lezioni'},
        ),
    ]
