# Generated by Django 5.1.7 on 2025-04-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lezioni', '0002_alter_lessonassignment_options'),
        ('student_groups', '0001_initial'),
        ('users', '0003_registrationtoken'),
    ]

    operations = [
        # 1. Add the 'group' field first
        migrations.AddField(
            model_name='lessonassignment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='student_groups.studentgroup', verbose_name='Gruppo Assegnato'),
        ),
        # 2. Now alter unique together constraints
        migrations.AlterUniqueTogether(
            name='lessonassignment',
            unique_together={('lesson', 'group'), ('lesson', 'student')},
        ),
        # 3. Alter other fields
        migrations.AlterField(
            model_name='lessonassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Assegnazione'),
        ),
        migrations.AlterField(
            model_name='lessonassignment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lezioni.lesson', verbose_name='Lezione Assegnata'),
        ),
        migrations.AlterField(
            model_name='lessonassignment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='users.student', verbose_name='Studente Assegnato (Individuale)'),
        ),
        migrations.AddConstraint(
            model_name='lessonassignment',
            constraint=models.CheckConstraint(condition=models.Q(('student__isnull', False), ('group__isnull', False), _connector='OR'), name='lesson_assignment_target_not_null', violation_error_message="L'assegnazione della lezione deve avere uno studente o un gruppo."),
        ),
        migrations.AddConstraint(
            model_name='lessonassignment',
            constraint=models.CheckConstraint(condition=models.Q(('student__isnull', False), ('group__isnull', False), _negated=True), name='lesson_assignment_target_exclusive', violation_error_message="L'assegnazione della lezione non può avere sia uno studente che un gruppo."),
        ),
        migrations.RemoveField(
            model_name='lessonassignment',
            name='assigned_by',
        ),
    ]
