# Generated by Django 5.1.7 on 2025-05-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lezioni', '0004_lessonassignment_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='content_type',
            field=models.CharField(choices=[('html', 'Contenuto HTML'), ('pdf', 'Documento PDF'), ('ppt', 'Presentazione PPT/PPTX'), ('url', 'Link Esterno'), ('file', 'File Scaricabile')], max_length=10, verbose_name='Tipo di Contenuto'),
        ),
    ]
