# Generated by Django 5.1.7 on 2025-05-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lezioni', '0005_alter_lessoncontent_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Ore Stimate Lezione'),
        ),
    ]
