# Generated by Django 5.1.7 on 2025-07-07 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lezioni', '0006_lesson_estimated_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Gruppo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_groups', to=settings.AUTH_USER_MODEL, verbose_name='Creatore')),
            ],
            options={
                'verbose_name': 'Gruppo di Lezioni',
                'verbose_name_plural': 'Gruppi di Lezioni',
                'unique_together': {('name', 'creator')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='lezioni.lessongroup', verbose_name='Gruppo'),
        ),
    ]
