# Generated by Django 5.1.7 on 2025-07-05 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_alter_student_preferred_badge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(help_text='Rich text content for the announcement modal.', verbose_name='Content')),
                ('is_active', models.BooleanField(default=True, help_text='Only active announcements will be shown.', verbose_name='Is Active')),
                ('is_important', models.BooleanField(default=False, help_text='Important announcements are shown first.', verbose_name='Is Important')),
                ('target_audience', models.CharField(choices=[('ALL', 'All Users'), ('TEACHERS', 'Teachers Only'), ('STUDENTS', 'Students Only')], default='ALL', max_length=10, verbose_name='Target Audience')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-is_important', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnnouncementView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_not_show_again', models.BooleanField(default=False, verbose_name='Do Not Show Again')),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='announcements.announcement')),
                ('student', models.ForeignKey(blank=True, help_text='The Student who viewed the announcement.', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('user', models.ForeignKey(blank=True, help_text='The User (teacher/admin) who viewed the announcement.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Announcement View',
                'verbose_name_plural': 'User Announcement Views',
                'constraints': [models.CheckConstraint(condition=models.Q(('user__isnull', False), ('student__isnull', False), _connector='OR'), name='user_or_student_is_not_null')],
                'unique_together': {('announcement', 'student'), ('announcement', 'user')},
            },
        ),
    ]
