# Generated by Django 5.1.7 on 2025-07-11 05:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Rich text content for the announcement modal.', verbose_name='Content'),
        ),
    ]
