# Generated by Django 5.1.7 on 2025-07-11 05:36

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_alter_announcement_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Rich text content for the announcement modal.', verbose_name='Content'),
        ),
    ]
