# Generated by Django 5.1.7 on 2025-03-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pin_hash',
            field=models.CharField(default='!', help_text="Hash del PIN numerico per l'accesso studente.", max_length=128, verbose_name='PIN Hash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_code',
            field=models.CharField(default='', help_text='Codice univoco identificativo dello studente (es. matricola).', max_length=50, unique=True, verbose_name='Student Code'),
            preserve_default=False,
        ),
    ]
