# Generated by Django 5.1.7 on 2025-04-21 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_pin_hash_student_student_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora di creazione del token.', verbose_name='Created At')),
                ('expires_at', models.DateTimeField(help_text='Data e ora di scadenza del token.', verbose_name='Expires At')),
                ('used_at', models.DateTimeField(blank=True, help_text='Data e ora in cui il token è stato utilizzato per la registrazione.', null=True, verbose_name='Used At')),
                ('student', models.OneToOneField(blank=True, help_text='Lo studente che si è registrato utilizzando questo token.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_token_used', to='users.student', verbose_name='Student Registered')),
                ('teacher', models.ForeignKey(help_text='Il docente che ha generato questo token.', limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='registration_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Registration Token',
                'verbose_name_plural': 'Registration Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
