# Generated by Django 5.1.7 on 2025-04-26 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_groups', '0002_alter_studentgroup_registration_token'),
        ('users', '0003_registrationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtoken',
            name='source_group',
            field=models.ForeignKey(blank=True, help_text='Il gruppo specifico per cui questo token è stato generato (se applicabile).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_tokens_generated', to='student_groups.studentgroup', verbose_name='Gruppo di Origine'),
        ),
    ]
