# Generated by Django 5.1.7 on 2025-04-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentgroup_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='students',
        ),
    ]
