# Generated by Django 5.1.7 on 2025-04-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_registrationtoken_source_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_public_groups',
            field=models.BooleanField(default=False, help_text='Designates whether the teacher can create public groups that other teachers can request access to.', verbose_name='Can Create Public Groups'),
        ),
    ]
