# Generated by Django 5.1.7 on 2025-04-14 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_studentgroup_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistrationToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se il token può essere ancora utilizzato.', verbose_name='Active')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_tokens', to='users.studentgroup', verbose_name='Group (Optional)')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='registration_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Student Registration Token',
                'verbose_name_plural': 'Student Registration Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
