# Generated by Django 5.1.7 on 2025-05-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_student_teacher_user_can_create_public_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='privacy_policy_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the student accepted the Privacy Policy.', null=True, verbose_name='Privacy Policy Accepted At'),
        ),
        migrations.AddField(
            model_name='student',
            name='terms_of_service_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the student accepted the Terms of Service.', null=True, verbose_name='Terms of Service Accepted At'),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_policy_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the user accepted the Privacy Policy.', null=True, verbose_name='Privacy Policy Accepted At'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_of_service_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the user accepted the Terms of Service.', null=True, verbose_name='Terms of Service Accepted At'),
        ),
    ]
