# Generated by Django 5.1.7 on 2025-05-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student_privacy_policy_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the deletion request was made.', null=True, verbose_name='Deletion Requested At'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_deletion_requested',
            field=models.BooleanField(default=False, help_text='Indicates if the student has requested account deletion.', verbose_name='Deletion Requested'),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the deletion request was made.', null=True, verbose_name='Deletion Requested At'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deletion_requested',
            field=models.BooleanField(default=False, help_text='Indicates if the user has requested account deletion.', verbose_name='Deletion Requested'),
        ),
    ]
