# Generated by Django 5.1.7 on 2025-05-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_student_deletion_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Student's date of birth, required for age verification.", null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='Email address of the parent or guardian for consent verification.', max_length=254, verbose_name='Parent/Guardian Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='parental_consent_denial_reason',
            field=models.TextField(blank=True, help_text='Reason provided if parental consent was denied (optional).', verbose_name='Parental Consent Denial Reason'),
        ),
        migrations.AddField(
            model_name='student',
            name='parental_consent_granted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when parental consent was granted.', null=True, verbose_name='Parental Consent Granted At'),
        ),
        migrations.AddField(
            model_name='student',
            name='parental_consent_requested_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when parental consent was requested.', null=True, verbose_name='Parental Consent Requested At'),
        ),
        migrations.AddField(
            model_name='student',
            name='parental_consent_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required (Age >= 14)'), ('PENDING', 'Pending Verification'), ('GRANTED', 'Granted'), ('DENIED', 'Denied')], default='NOT_REQUIRED', help_text='Status of parental consent for underage students.', max_length=20, verbose_name='Parental Consent Status'),
        ),
        migrations.AddField(
            model_name='student',
            name='parental_consent_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration timestamp for the verification token.', null=True, verbose_name='Parental Consent Token Expires At'),
        ),
        migrations.AddField(
            model_name='student',
            name='parental_consent_verification_token',
            field=models.UUIDField(blank=True, help_text='Unique token sent to the parent/guardian for verification.', null=True, unique=True, verbose_name='Parental Consent Verification Token'),
        ),
    ]
