# Generated by Django 5.1.7 on 2025-05-24 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0009_remove_badge_image_badge_file_badge_media_type_and_more'),
        ('users', '0008_student_date_of_birth_student_parent_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='preferred_badge',
            field=models.ForeignKey(blank=True, help_text='Il badge/ricompensa che lo studente ha scelto di visualizzare come preferito.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferring_students', to='rewards.reward', verbose_name='Badge Preferito'),
        ),
    ]
