# Generated by Django 5.1.7 on 2025-04-25 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_registrationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Gruppo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrizione (Opzionale)')),
                ('registration_token', models.CharField(blank=True, default=None, help_text="Token univoco per l'auto-registrazione degli studenti.", max_length=32, null=True, unique=True, verbose_name='Token di Registrazione')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'Docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_groups', to=settings.AUTH_USER_MODEL, verbose_name='Docente Proprietario')),
            ],
            options={
                'verbose_name': 'Gruppo di Studenti',
                'verbose_name_plural': 'Gruppi di Studenti',
                'ordering': ['teacher', 'name'],
                'unique_together': {('teacher', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudentGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Iscrizione al Gruppo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='student_groups.studentgroup', verbose_name='Gruppo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='users.student', verbose_name='Studente')),
            ],
            options={
                'verbose_name': 'Appartenenza a Gruppo',
                'verbose_name_plural': 'Appartenenze ai Gruppi',
                'ordering': ['group', 'student'],
                'unique_together': {('group', 'student')},
            },
        ),
    ]
