# Generated by Django 5.1.7 on 2025-04-26 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_groups', '0001_initial'),
        ('users', '0003_registrationtoken'),
    ]

    operations = [
        # Rimuoviamo il vecchio campo CharField (perdendo i dati esistenti)
        migrations.RemoveField(
            model_name='studentgroup',
            name='registration_token',
        ),
        # Aggiungiamo il nuovo campo OneToOneField
        migrations.AddField(
            model_name='studentgroup',
            name='registration_token',
            field=models.OneToOneField(blank=True, help_text='Token UUID associato a questo gruppo per la registrazione.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='users.registrationtoken', verbose_name='Token di Registrazione Associato'),
        ),
    ]
