# Generated by Django 5.1.7 on 2025-04-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extra data like image URL, link, etc. Inherited/overridden from template. Example: {"image_url": "http://example.com/reward.jpg"}', verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='rewardtemplate',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extra data like image URL, link, etc. Example: {"image_url": "http://example.com/img.png", "external_link": "http://info.example.com"}', verbose_name='Metadata'),
        ),
    ]
