# Generated by Django 5.1.7 on 2025-04-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_badge_earnedbadge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='image_url',
        ),
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, help_text='Immagine del badge (verrà caricata).', null=True, upload_to='badges/', verbose_name='Image'),
        ),
    ]
