# Generated by Django 5.1.7 on 2025-04-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_remove_badge_image_url_badge_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='trigger_condition',
            field=models.JSONField(blank=True, default=dict, help_text='Condizioni specifiche in formato JSON, dipendenti dal Trigger Type:\n<ul><li><b>QUIZ_COMPLETED:</b> <code>{"quiz_id": 123, "min_score_percent": 80}</code><br>   <i>(<code>quiz_id</code> è opzionale: se omesso, si applica al completamento di qualsiasi quiz.    <code>min_score_percent</code> è opzionale: se omesso, non viene controllato il punteggio.    Per il badge "Primo quiz completato", usare <code>{}</code>).</i></li><li><b>PATHWAY_COMPLETED:</b> <code>{"pathway_id": 45}</code><br>   <i>(<code>pathway_id</code> è opzionale: se omesso, si applica al completamento di qualsiasi percorso).</i></li><li><b>CORRECT_STREAK:</b> <code>{"streak_length": 10}</code><br>   <i>(Specifica la lunghezza minima della sequenza di risposte corrette consecutive).</i></li><li><b>POINTS_THRESHOLD:</b> <code>{"points": 500}</code><br>   <i>(Specifica la soglia di punti totali da raggiungere).</i></li></ul>', verbose_name='Trigger Condition'),
        ),
    ]
