# Generated by Django 5.1.7 on 2025-04-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_alter_badge_trigger_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_available_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Disponibilità')),
            ],
            options={
                'verbose_name': 'Disponibilità Ricompensa',
                'verbose_name_plural': 'Disponibilità Ricompense',
                'ordering': ['reward', 'group', 'student'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='rewardstudentspecificavailability',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rewardstudentspecificavailability',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='rewardstudentspecificavailability',
            name='student',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='available_to_specific_students',
        ),
        migrations.AlterField(
            model_name='reward',
            name='availability_type',
            field=models.CharField(choices=[('ALL', 'All Students of Teacher'), ('MANUAL', 'Manual Assignment (Specific Students/Groups)')], default='ALL', help_text="Defines the base availability rule. 'ALL' makes it available to all teacher's students. 'MANUAL' requires explicit assignment via RewardAvailability.", max_length=10, verbose_name='Availability'),
        ),
    ]
