# Generated by Django 5.1.7 on 2025-04-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0007_rewardavailability_group_rewardavailability_reward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
