# Generated by Django 5.1.7 on 2025-05-17 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0008_alter_reward_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='image',
        ),
        migrations.AddField(
            model_name='badge',
            name='file',
            field=models.FileField(blank=True, help_text='File principale del badge (immagine JPG/PNG/SVG, GIF, o video MP4).', null=True, upload_to='badges/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'gif', 'mp4'])], verbose_name='File'),
        ),
        migrations.AddField(
            model_name='badge',
            name='media_type',
            field=models.CharField(blank=True, choices=[('IMAGE_STATIC', 'Static Image (JPEG, PNG, SVG)'), ('IMAGE_GIF', 'Animated GIF'), ('VIDEO_MP4', 'Video (MP4)')], editable=False, help_text='Tipo di media, impostato automaticamente.', max_length=20, verbose_name='Media Type'),
        ),
        migrations.AddField(
            model_name='badge',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Anteprima statica opzionale per video o GIF animate, mostrata se il badge non è guadagnato.', null=True, upload_to='badges/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Thumbnail'),
        ),
    ]
