# Generated by Django 5.1.7 on 2025-05-10 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0021_alter_question_question_type_and_more'),
        ('lezioni', '0005_alter_lessoncontent_content_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='TODO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='udas', to='lezioni.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='udas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UDA',
                'verbose_name_plural': 'UDAs',
            },
        ),
        migrations.CreateModel(
            name='UDAContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('LESSON', 'Lesson'), ('QUIZ', 'Quiz'), ('NOTE', 'Note'), ('ACTIVITY', 'Activity')], max_length=20)),
                ('note_title', models.CharField(blank=True, max_length=255, null=True)),
                ('note_content', models.TextField(blank=True, null=True)),
                ('activity_title', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_description', models.TextField(blank=True, null=True)),
                ('activity_attachment_url', models.FileField(blank=True, null=True, upload_to='uda_attachments/')),
                ('activity_completed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lezioni.lesson')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.quiz')),
                ('uda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='uda.uda')),
            ],
            options={
                'verbose_name': 'UDA Content',
                'verbose_name_plural': 'UDA Contents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UDATemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uda_templates', to='lezioni.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uda_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UDA Template',
                'verbose_name_plural': 'UDA Templates',
            },
        ),
        migrations.AddField(
            model_name='uda',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_udas', to='uda.udatemplate'),
        ),
        migrations.CreateModel(
            name='UDATemplateContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('LESSON', 'Lesson'), ('QUIZ', 'Quiz'), ('NOTE_TEMPLATE', 'Note Template'), ('ACTIVITY_TEMPLATE', 'Activity Template')], max_length=20)),
                ('note_template_title', models.CharField(blank=True, max_length=255, null=True)),
                ('note_template_content', models.TextField(blank=True, null=True)),
                ('activity_template_title', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_template_description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lezioni.lesson')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.quiz')),
                ('uda_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='uda.udatemplate')),
            ],
            options={
                'verbose_name': 'UDA Template Content',
                'verbose_name_plural': 'UDA Template Contents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UDATemplateTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lezioni.topic')),
                ('udatemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uda.udatemplate')),
            ],
            options={
                'verbose_name': 'UDA Template Topic',
                'verbose_name_plural': 'UDA Template Topics',
                'unique_together': {('udatemplate', 'topic')},
            },
        ),
        migrations.AddField(
            model_name='udatemplate',
            name='topics',
            field=models.ManyToManyField(related_name='uda_templates', through='uda.UDATemplateTopic', to='lezioni.topic'),
        ),
        migrations.CreateModel(
            name='UDATopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lezioni.topic')),
                ('uda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uda.uda')),
            ],
            options={
                'verbose_name': 'UDA Topic',
                'verbose_name_plural': 'UDA Topics',
                'unique_together': {('uda', 'topic')},
            },
        ),
        migrations.AddField(
            model_name='uda',
            name='topics',
            field=models.ManyToManyField(related_name='udas', through='uda.UDATopic', to='lezioni.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='udatemplate',
            unique_together={('teacher', 'name')},
        ),
    ]
