# Generated by Django 5.1.7 on 2025-05-11 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lezioni', '0005_alter_lessoncontent_content_type'),
        ('uda', '0002_uda_order_in_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uda',
            name='subject',
        ),
        migrations.CreateModel(
            name='UDASubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lezioni.subject')),
                ('uda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uda.uda')),
            ],
            options={
                'verbose_name': 'UDA Subject',
                'verbose_name_plural': 'UDA Subjects',
                'unique_together': {('uda', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='uda',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='udas_multiple', through='uda.UDASubject', to='lezioni.subject'),
        ),
    ]
