# Generated by Django 5.1.7 on 2025-05-11 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0021_alter_question_question_type_and_more'),
        ('uda', '0003_remove_uda_subject_udasubject_uda_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='udacontent',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='udatemplatecontent',
            name='quiz',
        ),
        migrations.AddField(
            model_name='udacontent',
            name='quiz_template',
            field=models.ForeignKey(blank=True, help_text='Riferimento al template del quiz da cui istanziare un quiz concreto in un secondo momento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.quiztemplate'),
        ),
        migrations.AddField(
            model_name='udatemplatecontent',
            name='quiz_template',
            field=models.ForeignKey(blank=True, help_text='Riferimento al template del quiz', null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.quiztemplate'),
        ),
        migrations.AlterField(
            model_name='udacontent',
            name='content_type',
            field=models.CharField(choices=[('LESSON', 'Lesson'), ('QUIZ_TEMPLATE', 'Quiz Template'), ('NOTE', 'Note'), ('ACTIVITY', 'Activity')], max_length=20),
        ),
        migrations.AlterField(
            model_name='udatemplatecontent',
            name='content_type',
            field=models.CharField(choices=[('LESSON', 'Lesson'), ('QUIZ_TEMPLATE', 'Quiz Template'), ('NOTE_TEMPLATE', 'Note Template'), ('ACTIVITY_TEMPLATE', 'Activity Template')], max_length=20),
        ),
    ]
