# Generated by Django 5.1.7 on 2025-05-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uda', '0004_remove_udacontent_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udacontent',
            name='content_type',
            field=models.CharField(choices=[('LESSON', 'Lesson'), ('QUIZ', 'Quiz'), ('NOTE', 'Note'), ('ACTIVITY', 'Activity')], max_length=20),
        ),
    ]
