# Generated by Django 5.1.7 on 2025-05-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uda', '0005_alter_udacontent_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='udacontent',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Tempo stimato in ore (es. 1.5 per 1 ora e mezza)', max_digits=4, null=True),
        ),
    ]
