# Generated by Django with Roo assistance on 2025-05-14

from django.db import migrations, models


def find_and_assign_quiz_templates(apps, schema_editor):
    UDAContent = apps.get_model('uda', 'UDAContent')
    UDATemplateContent = apps.get_model('uda', 'UDATemplateContent')
    # QuizTemplate è in 'education' come confermato
    QuizTemplate = apps.get_model('education', 'QuizTemplate')

    problematic_contents = UDAContent.objects.filter(
        content_type='QUIZ',
        quiz_template__isnull=True
    )

    updated_count = 0
    warning_count = 0

    for content in problematic_contents:
        uda = content.uda
        assigned_quiz_template = None

        if uda.source_template:
            try:
                template_content_match = UDATemplateContent.objects.get(
                    uda_template=uda.source_template,
                    order=content.order,
                    content_type='QUIZ_TEMPLATE', # Cerca il tipo corretto nel template
                    quiz_template__isnull=False
                )
                assigned_quiz_template = template_content_match.quiz_template
            except UDATemplateContent.DoesNotExist:
                pass # Nessun contenuto template corrispondente
            except UDATemplateContent.MultipleObjectsReturned:
                print(f"WARNING: Multiple UDATemplateContent found for UDA '{uda.title}' (ID: {uda.id}), "
                      f"source template '{uda.source_template.name}' (ID: {uda.source_template.id}), "
                      f"order {content.order}. Cannot reliably assign quiz_template for UDAContent ID: {content.id}.")
                warning_count += 1
                continue

        if assigned_quiz_template:
            content.quiz_template = assigned_quiz_template
            content.save(update_fields=['quiz_template'])
            updated_count += 1
            print(f"INFO: Assigned quiz_template (ID: {assigned_quiz_template.id}) to UDAContent (ID: {content.id}) "
                  f"for UDA '{uda.title}' (ID: {uda.id}) from source template.")
        else:
            print(f"WARNING: Could not automatically assign quiz_template for UDAContent (ID: {content.id}) "
                  f"in UDA '{uda.title}' (ID: {uda.id}). "
                  f"UDA source template: {uda.source_template.name if uda.source_template else 'None'}. "
                  f"Please review manually.")
            warning_count += 1

    if updated_count > 0:
        print(f"\nSuccessfully updated {updated_count} UDAContent items with a quiz_template.")
    if warning_count > 0:
        print(f"Found {warning_count} UDAContent items that could not be automatically updated and require manual review.")
    if updated_count == 0 and warning_count == 0:
        print("\nNo UDAContent items found needing quiz_template assignment or all were already correct.")


class Migration(migrations.Migration):

    dependencies = [
        ('uda', '0007_udatemplatecontent_estimated_hours'),
        ('education', '0021_alter_question_question_type_and_more'), # Dipendenza dall'app education
    ]

    operations = [
        migrations.RunPython(find_and_assign_quiz_templates, migrations.RunPython.noop),
    ]