# Generated by Django 5.1.7 on 2025-05-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uda', '0008_fix_missing_quiz_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='uda',
            name='competences_html',
            field=models.TextField(blank=True, help_text='Contenuto HTML per le competenze', null=True),
        ),
        migrations.AddField(
            model_name='uda',
            name='knowledge_html',
            field=models.TextField(blank=True, help_text='Contenuto HTML per le conoscenze', null=True),
        ),
        migrations.AddField(
            model_name='uda',
            name='skills_html',
            field=models.TextField(blank=True, help_text='Contenuto HTML per le abilità', null=True),
        ),
    ]
