# Generated by Django 5.1.7 on 2025-05-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uda', '0009_uda_competences_html_uda_knowledge_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='udacontent',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Tempo effettivo impiegato in ore (es. 1.5 per 1 ora e mezza)', max_digits=4, null=True),
        ),
    ]
