# Generated by Django 5.1.7 on 2025-05-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uda', '0010_udacontent_actual_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='uda',
            name='assessment_type_html',
            field=models.TextField(blank=True, help_text='Contenuto HTML per il tipo di verifiche (export)', null=True),
        ),
        migrations.AddField(
            model_name='uda',
            name='didactic_strategies_html',
            field=models.TextField(blank=True, help_text='Contenuto HTML per le strategie didattiche (export)', null=True),
        ),
        migrations.AddField(
            model_name='uda',
            name='evaluation_html',
            field=models.TextField(blank=True, help_text='Contenuto HTML per la valutazione (export)', null=True),
        ),
        migrations.AddField(
            model_name='uda',
            name='export_specific_annotations_html',
            field=models.TextField(blank=True, help_text="Contenuto HTML per Annotazioni specifiche per l'export", null=True),
        ),
        migrations.AddField(
            model_name='uda',
            name='is_civic_education',
            field=models.BooleanField(default=False, help_text="Indica se l'UDA rientra nel percorso di Educazione Civica"),
        ),
        migrations.AddField(
            model_name='uda',
            name='materials_tools_html',
            field=models.TextField(blank=True, help_text='Contenuto HTML per materiali e strumenti (export)', null=True),
        ),
        migrations.AddField(
            model_name='uda',
            name='other_involved_subjects_text',
            field=models.TextField(blank=True, help_text='Testo libero per Altre Discipline Coinvolte (export)', null=True),
        ),
    ]
