# Generated by Django 5.1.7 on 2025-07-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uda', '0011_uda_assessment_type_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uda',
            name='key_and_citizenship_competences_html',
            field=models.TextField(blank=True, help_text='Contenuto HTML per le Competenze chiave e di cittadinanza (export)', null=True),
        ),
    ]
