# Generated by Django 5.1.7 on 2025-07-09 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uda', '0012_uda_key_and_citizenship_competences_html'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Group',
                'verbose_name_plural': 'Course Groups',
                'unique_together': {('teacher', 'name')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='uda.coursegroup'),
        ),
        migrations.CreateModel(
            name='UdaGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uda_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UDA Group',
                'verbose_name_plural': 'UDA Groups',
                'unique_together': {('teacher', 'name')},
            },
        ),
        migrations.AddField(
            model_name='uda',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='udas', to='uda.udagroup'),
        ),
    ]
