# Generated by Django 5.1.7 on 2025-07-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uda', '0013_coursegroup_course_group_udagroup_uda_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='uda',
            name='prerequisites_html',
            field=models.TextField(blank=True, help_text='Contenuto HTML per i prerequisiti', null=True),
        ),
    ]
