# Generated by Django 5.1.7 on 2025-07-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uda', '0014_uda_prerequisites_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='udacontent',
            old_name='activity_attachment_url',
            new_name='activity_attachment',
        ),
    ]
