# Generated by Django 5.1.7 on 2025-07-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uda', '0015_rename_activity_attachment_url_udacontent_activity_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='udacontent',
            name='activity_attachment',
        ),
    ]
