# Generated by Django 5.1.7 on 2025-03-27 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('users', '0002_student_pin_hash_student_student_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PathwayAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pathways', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='education.pathway', verbose_name='Pathway')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_assignments', to='users.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Pathway Assignment',
                'verbose_name_plural': 'Pathway Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('pathway', 'student')},
            },
        ),
        migrations.CreateModel(
            name='QuizAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='education.quiz', verbose_name='Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to='users.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Quiz Assignment',
                'verbose_name_plural': 'Quiz Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('quiz', 'student')},
            },
        ),
    ]
