# Generated by Django 5.1.7 on 2025-03-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_pathwayassignment_quizassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathwayprogress',
            name='first_correct_completion',
            field=models.BooleanField(default=False, help_text='Indicates if this is the first time the student successfully completed the pathway.', verbose_name='First Correct Completion?'),
        ),
    ]
