# Generated by Django 5.1.7 on 2025-04-04 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_pathwayquiztemplate_pathwaytemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztemplate',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_created_quiz_templates', to=settings.AUTH_USER_MODEL, verbose_name='Teacher Creator'),
        ),
        migrations.AlterField(
            model_name='quiztemplate',
            name='admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_created_quiz_templates', to=settings.AUTH_USER_MODEL, verbose_name='Admin Creator'),
        ),
        migrations.AddConstraint(
            model_name='quiztemplate',
            constraint=models.CheckConstraint(condition=models.Q(('admin__isnull', False), ('teacher__isnull', False), _connector='OR'), name='quiz_template_creator_check', violation_error_message='Un template di quiz deve avere un Admin o un Docente creatore.'),
        ),
        migrations.AddConstraint(
            model_name='quiztemplate',
            constraint=models.CheckConstraint(condition=models.Q(('admin__isnull', False), ('teacher__isnull', False), _negated=True), name='quiz_template_single_creator_check', violation_error_message='Un template di quiz non può avere sia un Admin che un Docente creatore.'),
        ),
    ]
