# Generated by Django 5.1.7 on 2025-04-04 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_quiztemplate_teacher_alter_quiztemplate_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathwayassignment',
            name='pathway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='education.pathway', verbose_name='Pathway'),
        ),
    ]
