# Generated by Django 5.1.7 on 2025-04-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_alter_pathwayassignment_pathway'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizassignment',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Optional deadline for the quiz assignment.', null=True, verbose_name='Due Date'),
        ),
    ]
