# Generated by Django 5.1.7 on 2025-04-09 09:18

from django.db import migrations


# Funzione per eliminare le righe PathwayAssignment con pathway nullo
def remove_null_pathway_assignments(apps, schema_editor):
    PathwayAssignment = apps.get_model('education', 'PathwayAssignment')
    # Non usare alias db qui, Django gestisce la connessione corretta
    deleted_count, _ = PathwayAssignment.objects.filter(pathway__isnull=True).delete()
    if deleted_count:
        print(f"    Deleted {deleted_count} PathwayAssignment records with null pathway.")

# Funzione per l'operazione inversa (non fa nulla in questo caso)
def noop_reverse(apps, schema_editor):
    pass
class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_quizassignment_due_date'),
    ]

    operations = [
        migrations.RunPython(remove_null_pathway_assignments, reverse_code=noop_reverse),
    ]
