# Generated by Django 5.1.7 on 2025-04-09 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_remove_null_pathway_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathwayassignment',
            options={'ordering': ['student', 'assigned_at'], 'verbose_name': 'Pathway Assignment', 'verbose_name_plural': 'Pathway Assignments'},
        ),
        migrations.AlterModelOptions(
            name='quizassignment',
            options={'ordering': ['student', 'assigned_at'], 'verbose_name': 'Quiz Assignment', 'verbose_name_plural': 'Quiz Assignments'},
        ),
        migrations.AddField(
            model_name='pathwayassignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='first_correct_completion',
            field=models.BooleanField(default=False, help_text='Indica se questo è stato il primo tentativo superato con successo per questo quiz da parte dello studente.', verbose_name='First Correct Completion?'),
        ),
        migrations.AlterField(
            model_name='pathwayassignment',
            name='assigned_by',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'TEACHER'), ('role', 'ADMIN'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pathways', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='pathwayassignment',
            name='pathway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='education.pathway', verbose_name='Pathway'),
        ),
        migrations.AlterField(
            model_name='quizassignment',
            name='assigned_by',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'TEACHER'), ('role', 'ADMIN'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='quizassignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
    ]
