# Generated by Django 5.1.7 on 2025-04-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_alter_pathwayassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathwayassignment',
            options={'ordering': ['pathway', 'group', 'student'], 'verbose_name': 'Assegnazione Percorso', 'verbose_name_plural': 'Assegnazioni Percorsi'},
        ),
        migrations.AlterModelOptions(
            name='quizassignment',
            options={'ordering': ['quiz', 'group', 'student'], 'verbose_name': 'Assegnazione Quiz', 'verbose_name_plural': 'Assegnazioni Quiz'},
        ),
    ]
