# Generated by Django 5.1.7 on 2025-04-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_alter_pathwayassignment_options_and_more'),
        ('student_groups', '0001_initial'),
        ('users', '0003_registrationtoken'),
    ]

    operations = [
        # 1. Add the 'group' fields first
        migrations.AddField(
            model_name='pathwayassignment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathway_assignments', to='student_groups.studentgroup', verbose_name='Gruppo Assegnato'),
        ),
        migrations.AddField(
            model_name='quizassignment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to='student_groups.studentgroup', verbose_name='Gruppo Assegnato'),
        ),
        # 2. Now alter unique together constraints
        migrations.AlterUniqueTogether(
            name='pathwayassignment',
            unique_together={('pathway', 'group'), ('pathway', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='quizassignment',
            unique_together={('quiz', 'group'), ('quiz', 'student')},
        ),
        # 3. Alter other fields (order relative to AddField is less critical here)
        migrations.AlterField(
            model_name='pathwayassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Assegnazione'),
        ),
        migrations.AlterField(
            model_name='pathwayassignment',
            name='pathway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='education.pathway', verbose_name='Percorso Assegnato'),
        ),
        migrations.AlterField(
            model_name='pathwayassignment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathway_assignments', to='users.student', verbose_name='Studente Assegnato (Individuale)'),
        ),
        migrations.AlterField(
            model_name='quizassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Assegnazione'),
        ),
        migrations.AlterField(
            model_name='quizassignment',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='education.quiz', verbose_name='Quiz Assegnato'),
        ),
        migrations.AlterField(
            model_name='quizassignment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to='users.student', verbose_name='Studente Assegnato (Individuale)'),
        ),
        migrations.AddConstraint(
            model_name='pathwayassignment',
            constraint=models.CheckConstraint(condition=models.Q(('student__isnull', False), ('group__isnull', False), _connector='OR'), name='pathway_assignment_target_not_null', violation_error_message="L'assegnazione del percorso deve avere uno studente o un gruppo."),
        ),
        migrations.AddConstraint(
            model_name='pathwayassignment',
            constraint=models.CheckConstraint(condition=models.Q(('student__isnull', False), ('group__isnull', False), _negated=True), name='pathway_assignment_target_exclusive', violation_error_message="L'assegnazione del percorso non può avere sia uno studente che un gruppo."),
        ),
        migrations.AddConstraint(
            model_name='quizassignment',
            constraint=models.CheckConstraint(condition=models.Q(('student__isnull', False), ('group__isnull', False), _connector='OR'), name='quiz_assignment_target_not_null', violation_error_message="L'assegnazione del quiz deve avere uno studente o un gruppo."),
        ),
        migrations.AddConstraint(
            model_name='quizassignment',
            constraint=models.CheckConstraint(condition=models.Q(('student__isnull', False), ('group__isnull', False), _negated=True), name='quiz_assignment_target_exclusive', violation_error_message="L'assegnazione del quiz non può avere sia uno studente che un gruppo."),
        ),
        migrations.RemoveField(
            model_name='pathwayassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='quizassignment',
            name='assigned_by',
        ),
    ]
