# Generated by Django 5.1.7 on 2025-05-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_quizassignment_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.CharField(blank=True, help_text='E.g., Mathematics, History', max_length=100, null=True, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.CharField(blank=True, help_text='E.g., Algebra, World War II', max_length=100, null=True, verbose_name='Topic'),
        ),
        migrations.AddField(
            model_name='quiztemplate',
            name='subject',
            field=models.CharField(blank=True, help_text='E.g., Mathematics, History', max_length=100, null=True, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='quiztemplate',
            name='topic',
            field=models.CharField(blank=True, help_text='E.g., Algebra, World War II', max_length=100, null=True, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='E.g., difficulty, completion_threshold_percent (0-100), points_on_completion. Example: {"difficulty": "hard", "completion_threshold_percent": 75.0, "points_on_completion": 10}', verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='quiztemplate',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extra data like difficulty ("easy", "medium", "hard"). Example: {"difficulty": "medium"}', verbose_name='Metadata'),
        ),
    ]
