# Generated by Django 5.1.7 on 2025-05-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_quiz_subject_quiz_topic_quiztemplate_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztemplate',
            name='card_background_color',
            field=models.CharField(blank=True, help_text='Hex color code for the quiz card background (e.g., #FFFFFF).', max_length=7, null=True, verbose_name='Card Background Color'),
        ),
    ]
