# Generated by Django 5.1.7 on 2025-05-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_quiztemplate_card_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='teacher_comment',
            field=models.TextField(blank=True, help_text='Feedback provided by the teacher for this answer, especially for open answers.', null=True, verbose_name='Teacher Comment'),
        ),
    ]
