# Generated by Django 5.1.7 on 2025-05-09 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0018_studentanswer_teacher_comment'),
        ('users', '0008_student_date_of_birth_student_parent_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Testo della notifica, es. \'Il tuo quiz "Nome Quiz" è stato corretto!\'', max_length=255, verbose_name='Message')),
                ('link', models.CharField(help_text="URL relativo per il frontend, es. '/quiz/attempt/123/result'", max_length=255, verbose_name='Link')),
                ('notification_type', models.CharField(choices=[('QUIZ_GRADED', 'Quiz Graded')], default='QUIZ_GRADED', max_length=50, verbose_name='Notification Type')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
