# Generated by Django 5.1.7 on 2025-05-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0020_alter_quizattempt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC_SINGLE', 'Multiple Choice (Single Answer)'), ('MC_MULTI', 'Multiple Choice (Multiple Answers)'), ('TF', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('OPEN_MANUAL', 'Open Answer (Manual Grading)')], max_length=20, verbose_name='Question Type'),
        ),
        migrations.AlterField(
            model_name='questiontemplate',
            name='question_type',
            field=models.CharField(choices=[('MC_SINGLE', 'Multiple Choice (Single Answer)'), ('MC_MULTI', 'Multiple Choice (Multiple Answers)'), ('TF', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('OPEN_MANUAL', 'Open Answer (Manual Grading)')], max_length=20, verbose_name='Question Type'),
        ),
    ]
