# Generated by Django 5.1.7 on 2025-05-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0021_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mc_single', 'Multiple Choice (Single Answer)'), ('mc_multi', 'Multiple Choice (Multiple Answers)'), ('tf', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('open_manual', 'Open Answer (Manual Grading)')], max_length=20, verbose_name='Question Type'),
        ),
        migrations.AlterField(
            model_name='questiontemplate',
            name='question_type',
            field=models.CharField(choices=[('mc_single', 'Multiple Choice (Single Answer)'), ('mc_multi', 'Multiple Choice (Multiple Answers)'), ('tf', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('open_manual', 'Open Answer (Manual Grading)')], max_length=20, verbose_name='Question Type'),
        ),
    ]
